[tool.poetry]
name = "itba-cde-pda"
version = "0.1.0"
description = ""
authors = ["fsantoliquido"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
google-api-python-client = "^2.145.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
