[tool.poetry]
name = "itba-cde-pda"
version = "0.1.0"
description = ""
authors = ["fsantoliquido"]
readme = "README.md"
packages = [{include = "airflow-etl/module_etl"}, {include = "airflow-etl/dags"}, {include = "airflow-etl/tests"}]  


[tool.poetry.dependencies]
python = ">=3.8,<3.9"
google-api-python-client = "^2.145.0"
pandas = "1.5.3"
ipykernel = "^6.29.5"
isodate = "^0.6.1"
sqlalchemy = "1.4.46"
psycopg2 = "^2.9.9"
sqlalchemy-redshift = "^0.8.14"
pytest = "^8.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test = "env PYTHONPATH=.:pytest"